const FRIENDS = 'FRIENDS' as const;
const PENDING_FIRST_SECOND = 'PENDING_FIRST_SECOND' as const;
const PENDING_SECOND_FIRST = 'PENDING_SECOND_FIRST' as const;
const BLOCK_FIRST_SECOND = 'BLOCK_FIRST_SECOND' as const;
const BLOCK_SECOND_FIRST = 'BLOCK_SECOND_FIRST' as const;
const BLOCK_BOTH = 'BLOCK_BOTH' as const;

export const FriendshipStatuses = {
  FRIENDS,
  PENDING_FIRST_SECOND,
  PENDING_SECOND_FIRST,
  BLOCK_FIRST_SECOND,
  BLOCK_SECOND_FIRST,
  BLOCK_BOTH,
};

export const INCOMING_FRIENDSHIP_REQUEST = 'INCOMING';
export const PENDING_FRIENDSHIP_REQUEST = 'PENDING';
