export const VIEW_USERS_PERMISSION = 'VIEW_USERS_PERMISSION';
export const BAN_USERS_PERMISSION = 'BAN_USERS_PERMISSION';
export const DELETE_USERS_PERMISSION = 'DELETE_USERS_PERMISSION';
export const SEND_MESSAGES_PERMISSION = 'SEND_MESSAGES_PERMISSION';

export const PERMISSIONS = {
  VIEW_USERS_PERMISSION,
  BAN_USERS_PERMISSION,
  DELETE_USERS_PERMISSION,
  SEND_MESSAGES_PERMISSION,
};
